# sim.cohesion.R

# assume popn generated by cluster process and parents, parentid saved

sim.cohesion <- function(traps, popn, detectfn = 0, detectpar = list(), 
						 noccasions = 5, savepopn = FALSE, gamma = 1, ...) {
	covariates(popn) <- NULL
	parentpop <- attr(popn, "parents")
	if (is.null(parentpop) || length(parentpop)==0)
		stop ("requires popn with parents attribute")
	class(parentpop) <- class(popn)
	alone <- runif(nrow(popn)) < (1-gamma)
	arg <- list(...)
	arg$traps <- traps
	arg$renumber <- FALSE
	arg$popn <- subset(popn, alone)
	arg$detectfn <- detectfn
	arg$detectpar <- detectpar
	arg$noccasions <- noccasions
	ch <- do.call(sim.capthist, arg)
	if (gamma>0) {
		arg$popn <- parentpop
		chparents <- do.call(sim.capthist, arg)
		# clone histories of _detected_ parents, one for each offpring
		parentid <- attr(popn, "parentid")
		parentid[alone] <- 0         # ignore 'lone' animals 
		parfreq <- tabulate (parentid, nbins = nrow(parentpop)) # frequency by parent
		parfreq <- parfreq[rownames(parentpop) %in% rownames(chparents)]
		if (any(parfreq>0)) {     # otherwise ch remains as before
			chgroup <- try(clone(chparents, type = 'constant', parfreq))
			if (inherits(chgroup, 'try-error')) browser()
			ch <- rbind(chgroup, ch, verify = FALSE)
		}
	}
	if (savepopn) attr(ch, 'popn') <- popn
	ch
}
